### DISCUSSION TITLE
No more AWS support?

### DISCUSSION THREAD

**Discussion by joaogbcravo** [jodevsa/wireguard-operator#80] [Q&A] [answered]
After updating to the last versions, I notice that the service is not being annotated anymore with

```
"service.beta.kubernetes.io/aws-load-balancer-type":            "external",
"service.beta.kubernetes.io/aws-load-balancer-nlb-target-type": "ip",
"service.beta.kubernetes.io/aws-load-balancer-scheme":          "internet-facing",
```

Which was being injected by a file that doesn't exist anymore './controllers/wireguard_controller.go:'

Is this feature moved to another place? I don't see it. 
Should I create some PR to add back the EKS support?

**Comment by jodevsa** [comment]
Hi @joaogbcravo,


I can also confirm the problem from my side :( 


We have removed the default AWS service annotations in this PR and replaced them by the ability to let users control those annotations. For example you can create the following VPN deployment with the AWS service annotations:



```
apiVersion: vpn.example.com/v1alpha1
kind: Wireguard
metadata:
  name: "my-cool-vpn-123"
spec:
  mtu: "1380"
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
  serviceType: NodePort


```

the serviceAnnotations field in wireguard.spec will forward those annotations to the service created by wireguard-operator.







> Should I create some PR to add back the EKS support?

that would be great! I think even though we have a workaround today it would still be better to make wireguard-operator work out of the box for everyone. So it would be great if we create some logic that detects that the operator is being used in EKS and automatically adds those annotations.
