### ISSUE TITLE
Peers can't contact eachother over the network

### ISSUE THREAD

**Issue by Twi** [jodevsa/wireguard-operator#180]
**Describe the bug**
I want to create a network such that peers can contact eachother as if they were on the same physical network segment.

**To Reproduce**

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
  name: "ponyville"
  namespace: wireguard
spec:
  mtu: "1380"
  serviceType: "NodePort"
  enableIpForwardOnPodInit: true
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: rainbow-dash
  namespace: wireguard
spec:
  wireguardRef: "ponyville"
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: rarity
  namespace: wireguard
spec:
  wireguardRef: "ponyville"
```

**Expected behavior**
Node `rainbow-dash` to be able to ping node `rarity` and connect over TCP/UDP/IP.

**Additional context**
