### ISSUE TITLE
No readiness and liveness probe defined for wg-agent container

### ISSUE THREAD

**Issue by winston0410** [jodevsa/wireguard-operator#187]
**Is your feature request related to a problem? Please describe.**
At the moment no readiness and liveness probe is defined for the wg-agent container generated by `Wireguard` CRD. It makes it impossible for K8S to 1. restart the deployment(that should happen when liveness probe fail) or 2. prevent sending traffic to an unready wg-agent(that should happen when readiness probe fail)

**Describe the solution you'd like**
Define both liveness and readiness probes for the CRD. For liveness and readiness probes, it support checking with HTTP, TCP and gRPC. I guess setting up an HTTP check will be the simplest.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes

- For the wg-agent, we will need to create a health check route. 
- For the manifest, we need to set up two probes. As they should be different, I suggest using `tcpSocket` for livenessProbe and `httpGet` for the readinessProbe. Assuming port 8080 is used to expose the HTTP endpoint:

```yaml
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
```

And for the `/health` route, we need to make sure wg-agent is ready to accept traffic at 51820 UDP.

**Describe alternatives you've considered**
This is the most K8S native way

**Additional context**
