### ISSUE TITLE
Operation cannot be fulfilled - the object has been modified

### ISSUE THREAD

**Issue by pavel-trubitsyn** [jodevsa/wireguard-operator#208]
Controller manager returns after peer creation:

> 2024-08-13T12:18:07Z	INFO	Updating secret with new config	{"controller": "wireguard", "controllerGroup": "vpn.wireguard-operator.io", "controllerKind": "Wireguard", "Wireguard": {"name":"wg","namespace":"wireguard-system"}, "namespace": "wireguard-system", "name": "wg", "reconcileID": "bb21cd81-d365-4dd2-808f-4f71c8e5b31a"}
...
2024-08-13T12:18:07Z	ERROR	Reconciler error	{"controller": "wireguardpeer", "controllerGroup": "vpn.wireguard-operator.io", "controllerKind": "WireguardPeer", "WireguardPeer": {"name":"test","namespace":"wireguard-system"}, "namespace": "wireguard-system", "name": "test", "reconcileID": "b97c02d3-2209-4c49-b105-ee6c29cd3848", "error": "Operation cannot be fulfilled on wireguardpeers.vpn.wireguard-operator.io \"test\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:324
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226
...
2024-08-13T12:18:07Z	INFO	updated pod	{"controller": "wireguard", "controllerGroup": "vpn.wireguard-operator.io", "controllerKind": "Wireguard", "Wireguard": {"name":"wg","namespace":"wireguard-system"}, "namespace": "wireguard-system", "name": "wg", "reconcileID": "bb21cd81-d365-4dd2-808f-4f71c8e5b31a"}

**To Reproduce**
1. Create server: 
```yaml
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
  name: wg
  namespace: wireguard-system
spec:
  serviceType: LoadBalancer
  mtu: "1280"
  address: 1.2.3.4
  dns: 10.31.0.10
```
2. Create Peer: 
```yaml
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: test
  namespace: wireguard-system
spec:
  wireguardRef: "wg"
```
3. See error in manager log

Version: 2.1.0
Iptables on node:
![screenshot](https://github.com/user-attachments/assets/74474ab7-6ba6-4780-928a-17922e3edd70)
