### ISSUE TITLE
Allow Setting Custom label on Service

### ISSUE THREAD

**Issue by jseiser** [jodevsa/wireguard-operator#213]
**Is your feature request related to a problem? Please describe.**
We have multiple external-dns configurations, so we use labels to inform which external-dns should handle creating the DNS for an Ingress/Service.

**Describe the solution you'd like**
```
apiVersion: vpn.example.com/v1alpha1
kind: Wireguard
metadata:
  name: "trex-ng-wg"
spec:
  serviceAnnotations:
    custom: label
```
