### ISSUE TITLE
Way to Health Check from Load Balancer

### ISSUE THREAD

**Issue by jseiser** [jodevsa/wireguard-operator#214]
**Is your feature request related to a problem? Please describe.**
There should be a way to determine the health of the VPN from the load balancer.  Creating an public NLB in AWS.

```
Annotations:              
                          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
                          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes:
                          service.beta.kubernetes.io/aws-load-balancer-type: external
```

You end up with a UDP listener like you would expect, but an NLB can only health check via TCP, HTTP, or HTTPS.

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html

So the service is down and no traffic is routed.

**Describe the solution you'd like**

Ideally the agent container exposes some sort of healthcheck via HTTP.
