### ISSUE TITLE
Labels to differentiate peers

### ISSUE THREAD

**Issue by UrfinJuice11** [jodevsa/wireguard-operator#26]
**Is your feature request related to a problem? Please describe.**
I have implemented a WG server in test environment, two peers (A and B) and two different test namespaces (let's say AAA and BBB). I need to perform network policies in order to allow peer A to connect only namespace AAA. And peer B should be able to reach only the namespace BBB. 
But when I look at the cluster traffic with Cilium I see that there is no difference between peer's A and B connection sources.
Both connections have the same "wireguard-system" namespace, same IP address, same labels of WG deployment. 

![image](https://user-images.githubusercontent.com/33019945/227581398-d03fbb30-363b-4f75-a0df-f5ae452715ee.png)

Also, If I understood right, I am not allowed to create "wireguardpeer" instances in any namespace except the WG server's namespace.

**Describe the solution you'd like**
In case there is no existing walkaround for the issue, maybe it would be useful to have some kind of labels to differentiate the peers...

P.S. Thanks for the solution! It is extremely useful in my project.

**Comment by jodevsa** [comment]
Hi @UrfinJuice11, 

I'll write more info soon but will leave a quick hint now:

You'll need to create 2 Wireguard server instances. One called "A" on namespace "A" and another called "B" on namespace "B". if you want a user to only connect to namespace A then create a peer for them on wire-guard server A and then create a network policy that makes sure wireguard A only can speak with pods in namespace A

**Comment by jodevsa** [comment]
are you available for a quick chat about it?

**Comment by jodevsa** [comment]
https://meet.google.com/bii-vnud-mhp?authuser=0&pli=1

**Comment by UrfinJuice11** [comment]
What about a solution, where access controls are implemented not at the CNI level, but at the WG server level?
For example, we create a `wireguardpeer` instance with smth like `allowed_destination_ip` (don't mess with allowedIPs in WG config). Then while creating a record in server's wg0.conf this `allowed_destination_ip` value will be written in PreUP declaration with an iptables rule. 
Since services in different namespaces have different IP-addresses, we can use these addresses to differentiate clients' flows.

**Comment by UrfinJuice11** [comment]
My situation is the following:

![image](https://user-images.githubusercontent.com/33019945/227916449-5413727c-9e3a-4774-942e-f9e73338c82e.png)

Even now my project can be alive, if there will be a way to mention PostUp iptables rules while creating `wireguardpeers`. But at this setup I need to:

1. create the `wireguardpeer` with some IPs (or maybe IP range, like 10.0.0.0/30) in PostUp rules.
2. only then create the Alice namespace and explicitly create her services on the mentioned IP or IP ranges.

This variant is good for me because the Alice's pod will be alive for a short period of time. And all I need is a way to add PostUp and PostDown rules to [Peer] sections of  `wireguardpeer`. Is it possible to add this functionality?

But, I suppose that this solution will cover only my scenario, and in order to make wireguard-operator more universal, the trick with  endpoints and DNS-names should be more reasonable.

**Comment by jodevsa** [comment]
Thanks for the explanation.

> This variant is good for me because the Alice's pod will be alive for a short period of time. And all I need is a way to add PostUp and PostDown rules to [Peer] sections of wireguardpeer. Is it possible to add this functionality?
Can you give me an example of what iptable command you will be running in PostUp and PostDown of the peer section?

**Comment by jodevsa** [comment]
I think you'll need to use the peer IP in the iptable rule so we probably need to expose it as an enviroment variable so that your postUp/postDown script can use it

**Comment by jodevsa** [comment]
I'm thinking of something like this; what do you think?
```
apiVersion: vpn.example.com/v1alpha1
kind: WireguardPeer
metadata:
  name: peer1
spec:
  wireguardRef: "my-cool-vpn"
  postUp: "iptables -I OUTPUT --source $PEER_IP -d  8.8.8.8 -j ACCEPT"
```

$PEER_IP is an enviroment variable that will be populated with the actual peer IP

**Comment by jodevsa** [comment]
another idea that involves some abstractions similar to the ones in NetworkPolicy

```
apiVersion: vpn.example.com/v1alpha1
kind: WireguardPeer
metadata:
  name: peer1
spec:
  wireguardRef: "my-cool-vpn"
  networkPolicy:
    Egress:
     - action: DENY 
        destination:
            IP: 8.8.8.8
```

**Comment by UrfinJuice11** [comment]
Yes, that's exactly I am talking about. 

So, the wg0.conf of the server will be smth. like:

```[Interface]
PrivateKey = <server-private-key>
Address = 10.0.0.1/24
ListenPort = <server-port>

[Peer]
PublicKey = <peer1-public-key>
AllowedIPs = 10.0.0.2/32, 192.168.0.2/32
PostUp = iptables -A FORWARD -i wg0 -o eth0 -s 10.0.0.2/32 -d 192.168.0.2/32 -j ACCEPT

[Peer]
PublicKey = <peer2-public-key>
AllowedIPs = 10.0.0.3/32, 192.168.0.3/32
PostUp = iptables -A FORWARD -i wg0 -o eth0 -s 10.0.0.3/32 -d 192.168.0.3/32  -j ACCEPT
```

But also there should be the contraversal operation like PostDown in order to delete the rules after the peer is dead.

Now, I should think by myself what would be the workflow in my case. I mean if the peer config is created before namespace, than there are no problems, because I can get the destination address 192.168.0.2/32 or 192.168.0.2/30 with `kubectl get wireguardpeer` and create the namespace with that address. 

Anyway it is my own problem. But. I think that adding the PreUp, PostUp, PreDown, PostDown, Address, AllowedIPs sections to the `wireguardpeer` yaml would be good in any practical case.

**Comment by UrfinJuice11** [comment]
> another idea that involves some abstractions similar to the ones in NetworkPolicy
> 
> ```
> apiVersion: vpn.example.com/v1alpha1
> kind: WireguardPeer
> metadata:
>   name: peer1
> spec:
>   wireguardRef: "my-cool-vpn"
>   networkPolicy:
>     egress:
>      - action: Allow 
>         destination:
>             IP: 8.8.8.8
> ```
> 
> I like this more as it would be easier for the average user and doesn't need expertise in iptables. We also need to implement an implicit DENY all behaviour similar to the behaviour of GlobalNetworkPolicy/NetworkPolicy.
> 
> Does implementing something like this cover your case?

Suppose, that this variant is even better. But it depends on my own flow. Which resources are created first. If there is a chance to use not IP: 8.8.8.8, but namespace: Alice, then it will completely resolve my issue.

**Comment by jodevsa** [comment]
> Suppose, that this variant is even better. But it depends on my own flow. Which resources are created first. If there is a chance to use not IP: 8.8.8.8, but namespace: Alice, then it will completely resolve my issue.

Filtering by namespace is a complex task; I'm thinking of deliviring this feature in multiple phases to break the work in smaller chunks and make delivery possible


initial plan:



- egress rules for destination IP (Phase 1)
```
apiVersion: vpn.example.com/v1alpha1
kind: WireguardPeer
metadata:
  name: peer1
spec:
  wireguardRef: "my-cool-vpn"
  networkPolicy:
    egress:
     - action: Allow 
        destination:
            IP: 8.8.8.8
```
- egress rules based on kubernetes service (Phase 2)
```
apiVersion: vpn.example.com/v1alpha1
kind: WireguardPeer
metadata:
  name: peer1
spec:
  wireguardRef: "my-cool-vpn"
  networkPolicy:
    egress:
     - action: Allow 
        destination:
            service:
                 service: "service-1"
                 namespace: "A"
```
- egress rules based on namespace (phase3)
```
apiVersion: vpn.example.com/v1alpha1
kind: WireguardPeer
metadata:
  name: peer1
spec:
  wireguardRef: "my-cool-vpn"
  networkPolicy:
    egress:
     - action: Allow 
        namespace:
            IP: 8.8.8.8
```

**Comment by jodevsa** [comment]
> and create the namespace with that address.
What do you mean by that?

**Comment by UrfinJuice11** [comment]
Oh, I mean create namespace and a service in that namespace with an explicitly set IP address.

**Comment by jodevsa** [comment]
> Oh, I mean create namespace and a service in that namespace with an explicitly set IP address.

So probably phase 1 will cover your case (I know it's not convenient but I hope this will unblock you): 
> apiVersion: vpn.example.com/v1alpha1
> kind: WireguardPeer
> metadata:
>   name: peer1
> spec:
>   wireguardRef: "my-cool-vpn"
>   networkPolicy:
>     egress:
>      - action: Allow 
>         destination:
>             IP: 8.8.8.8

**Comment by jodevsa** [comment]
phase 1 implementation ideas:


We'll probably rely on `iptables-restore` to apply new rules every time a Peer is updated. The logic should be idempotent and does not cause any downtime while updating the iptables rules. The operator should inject the iptables rules into the pod of the wireguard server that would look like something like this:
```
*filter

# rules for peer 10.8.0.2
:10.8.0.2 - [0:0]
-A FORWARD -s 10.8.0.2/32 -j 10.8.0.2
-A 10.8.0.2 -d 10.8.0.1/32 -j ACCEPT
-A 10.8.0.2 -d 100.64.0.10/32 -j ACCEPT
-A 10.8.0.2 -j REJECT --reject-with icmp-port-unreachable

# rules for peer 10.8.0.3
:10.8.0.3 - [0:0]
-A FORWARD -s 10.8.0.3/32 -j 10.8.0.3
-A 10.8.0.3 -d 10.8.0.1/32 -j ACCEPT
-A 10.8.0.3 -d 100.64.0.10/32 -j ACCEPT -m comment --comment "include the json of this rule for debugging purposes"
-A 10.8.0.3 -j REJECT --reject-with icmp-port-unreachable -m comment --comment "implicit reject all"

COMMIT

*nat
:PREROUTING ACCEPT [4234:819045]
:INPUT ACCEPT [14:2125]
:OUTPUT ACCEPT [345:23125]
:POSTROUTING ACCEPT [347:23299]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT

```

**Comment by jodevsa** [comment]
more insights about iptables and how to update rules in an atomic way: https://isawan.net/posts/atomic-iptables-script

**Comment by jodevsa** [comment]
Hi @UrfinJuice11,

I have good news; I'm done with phase 1 https://github.com/jodevsa/wireguard-operator/pull/28; it still needs some cleaning but the feature works!! hopefully I'll merge it in the next days

**Comment by jodevsa** [comment]
here is how the config looks like
```
spec:
  PrivateKeyRef:
    secretKeyRef:
      key: privateKey
      name: peer20-peer
  address: 10.8.0.2
  egressNetworkPolicies:
  - action: Accept
    protocol: UDP
    to:
      ip: 8.8.8.8
      port: "53"
  - action: Accept
    protocol: TCP
    to:
      ip: 202.78.174.252
      port: "6443"
```
