### ISSUE TITLE
Add a set of default required annotations on the LoadBalancer service for popular cloud providers

### ISSUE THREAD

**Issue by Matthew-Beckett** [jodevsa/wireguard-operator#43]
**Is your feature request related to a problem? Please describe.**

Currently the annotations added to the load balancer are hard coded, soon you'll be able to provide a set of annotations in the spec.

However, I believe it should be possible to enable a set of default annotations for cloud providers such as AWS, GCP etc.

**Describe the solution you'd like**

I propose something like the following:

```yaml
apiVersion: vpn.example.com/v1alpha1
kind: Wireguard
metadata:
  name: vpn
spec:
  serviceAnnotations:
    foo.bar/bar.foo: true
  providers:
    aws:
      enableDefaultAnnotations: true
```

This would append and merge the default annotations required by AWS for example and also any additional annotations required for other controllers such as cert-manager, external-dns etc.
